### ISSUE TITLE
The android Docker image does not build on nightly

### ISSUE THREAD

**Issue by muhammadali286** [overhangio/tutor-android#11]
Getting this error while building image with nightly.

_This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered._

<img width="1440" alt="Screenshot 2023-11-07 at 6 45 46 PM" src="https://github.com/overhangio/tutor-android/assets/42408263/771b2087-4944-4f95-a51d-8ab90238583d">

**Comment by muhammadali286** [comment]
Hi, 
I am trying to install tutor android plugin with tutor nightly and currently facing two challenges. 

1. We do not mention build tools version in android app after Gradle 3 ([Ref](https://developer.android.com/tools/releases/build-tools)).  Android build tasks are trying to install build tool `30.0.3` on Ubuntu image as build tool has not mentioned in edx android which has its own bug and can not be installed ([issue details](https://github.com/741g/android-emulator-m1-preview/issues/14)). Possible solutions are 
    i. We can ask Edx mobile to to explicitly mention build tool version.
    ii. We can fork the the repo in which we can add the version. It is not recommended because we will have to manage the repo with latest code. 
    iii. After cloning, script will edit the `build.gradle` file with adding build tool version.
    iv. We can try building image with other versions of OS. I have personally run all the commands on mac and its working fine on mac. android dependencies differ from one OS to other.

2. We have two different services for android app i.e `android` and `android-app` while building image we can only build `android` one, but on launch command it is building `android-app`. I am unable to figure out the purpose of these images would appreciate if someone explain it to me.

**Comment by regisb** [comment]
Thanks for investigating this issue @muhammadali286.

- 1.i would be great, but it's going to be some time before any PR is merged. This approach could be combined with 1.iii. (see below)
- 1.ii is not acceptable, because we don't want to maintain a long-lived fork.
- 1.iii is totally possible. We could for instance open a PR (see 1.i) and until that PR is merged, cherry-pick a commit from one of our forks in the Dockerfile, similar to what we do in the "openedx" Docker image: https://github.com/overhangio/tutor/blob/65ba0d2de24a1ac0e9e91404dcd28eed9cbfd9a1/tutor/templates/build/openedx/Dockerfile#L55 : `RUN curl -fsSL https://github.com/openedx/edx-app-androidcommit/<GITSHA1>.patch | git am `
- Solution 1.iv would be great. Does that mean changing "`FROM docker.io/ubuntu:22.04 AS base`" in https://github.com/overhangio/tutor-android/blob/master/tutorandroid/templates/android/build/Dockerfile#L1? Which OS would work?

> We have two different services for android app i.e android and android-app while building image we can only build android one, but on launch command it is building android-app. I am unable to figure out the purpose of these images would appreciate if someone explain it to me.

The "android" image is the image that contains all the tools to later build the app. This image does not contain any user-specific configuration, and thus it is pushed to Docker Hub: https://hub.docker.com/r/overhangio/openedx-android

The "android-app" image, on the other hand, contains a lot of user-specific configuration, so we cannot push it to Docker Hub. We need to re-build it every time the configuration changes, which can be quite often.

We could bundle both build tools and application in a single image, but then the build time would be very long. So we put as much of the build steps as possible in the pre-built "android" image.
