### ISSUE TITLE
Deprecation/Removal: edx-mobile-ios & edx-mobile-android

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-android#20]
Old codebases are shifting and no longer be the primary Open edX iOS mobile apps, starting with the Redwood release. The proposed deadline is April 10, 2024.
The new mobile repositories are maintained by Raccoon Gang and can be accessed here:
https://github.com/openedx/openedx-app-ios
https://github.com/openedx/openedx-app-android

https://discuss.openedx.org/t/deprecation-removal-edx-mobile-ios-edx-mobile-android-https-github-com-openedx-edx-app-ios-issues-1804-1804/12430
https://github.com/openedx/public-engineering/issues/260
https://github.com/openedx/public-engineering/issues/261
@regisb

**Comment by regisb** [comment]
@DawoudSheraz we need to update this plugin to build the new android mobile app, instead of the old one. For that, we should sync up both with Raccoon Gang and with the Edly team which is in charge of helping 2U build the app. Unless I'm mistaken, the Edly mobile team is supposed to deliver a new version by the end of March. This is a rather complex project, and we need to deliver it by Redwood. Can the team start working on it as soon as possible?

**Comment by DawoudSheraz** [comment]
@Abdul-Muqadim-Arbisoft @hamza-56 Please provide the latest update on this. Thanks

**Comment by Abdul-Muqadim-Arbisoft** [comment]
[PR](https://github.com/overhangio/tutor-android/pull/21) has been made in for upgradation  of tutor-android to build new openedx android mobile app

**Comment by DawoudSheraz** [comment]
@hamza-56 Please add the updates on the issue. Thank you.

**Comment by DawoudSheraz** [comment]
1. https://github.com/overhangio/tutor-android/pull/21 -- First PR that made Dockerfile changes
2. https://github.com/overhangio/tutor-android/pull/22 -- Config changes
3. https://github.com/overhangio/tutor-android/pull/23 -- small dockerfile change to cater to OPENEDX_COMMON_VERSION
